spring.application.name=DBSpringBoot

server.port=8080

# 1. Cambiamos las variables ${} por tus credenciales locales directas
spring.datasource.url=jdbc:postgresql://localhost:5432/club_nautico?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=msj123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 2. Dejamos valores fijos para JWT evitando que busquen variables de entorno vacías
jwt.secret=Kovy9vgQDX/VA3G9pk2a0f1jK5VTo+WGf0cIpWjeFCs=
jwt.expiration=86400000
