spring.application.name=DBSpringBoot
server.port=8080

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}?sslmode=require&channelBinding=require&stringtype=unspecified
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
