spring.application.name=DBSpringBoot
#driver?
# env parametros de conexion a la DB
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/club_nautico
spring.datasource.username=postgres
spring.datasource.password=msj123
#cambiar en produccion a none
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
